services:
  - type: web
    name: flask-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:main  
    envVars:
      - key: SOME_API_KEY
        value: your_flask_api_key_if_any
    rootDir: flask-api  # folder where your Flask app lives
