services:
  - type: web
    name: node backend
    env: node
    buildCommand: npm install
    startCommand: node server.js  
    envVars:
      - key: MONGO_URI
        value: your_mongodb_connection_string
      - key: FLASK_API_URL
        value: https://your-flask-api.onrender.com  # used to call your ML service
    rootDir: node backend  # folder where your Node.js backend lives

  - type: web
    name: flask-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:main  
    envVars:
      - key: SOME_API_KEY
        value: your_flask_api_key_if_any
    rootDir: flask-api  # folder where your Flask app lives
