services:
  - type: web
    name: flask-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app  
    envVars:
      - key: SOME_API_KEY
        value: https://phisherman-974c.onrender.com/
    rootDir: flask-api  
